"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var stringUtils_1 = require("./stringUtils");
var fs = require("fs");
var path = require("path");
var sentence = "Learning Node.js is important because you can write efficient server-side applications.";
var reversedSentence = (0, stringUtils_1.reverseString)(sentence);
fs.writeFileSync('reversed.txt', reversedSentence);
console.log("Original Sentence: ", sentence);
console.log("Reversed Sentence: ", reversedSentence);
fs.writeFileSync('reversed.txt', 'Hello, world!');
var filePath = path.join(__dirname, 'reversed.txt');
console.log('File path:', filePath);
